name: TEST Update Housing Scraper

on:
  push:
    branches:
      - dev

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout scraper repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: List all directories
      run: |
        ls -R

    - name: Run scraper script
      run: |
        python scraper.py

    - name: Checkout GitHub Pages repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
        repository: celestegambardella/celestegambardella.github.io
        ref: prod  # Checkout the prod branch
        path: dist  # This checks out the GitHub Pages repo to the "dist" directory

    - name: List output directory
      run: |
        dir=pwd
        ls -la ${dir}/src/output

    - name: Copy markdown to GitHub Pages repo
      run: |
        cp $GITHUB_WORKSPACE/output/hausing-scraper.md dist/src/content/work/hausing-scrapper.md
        cat $GITHUB_WORKSPACE/output/hausing-scraper.md