name: Update Hausing Scraper

on:
#  schedule:
#    - cron: '0 * * * *'  # Run hourly
#  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout scraper repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scraper script
      run: |
        python src/scraper.py

    - name: Checkout GitHub Pages repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
        repository: celestegambardella/celestegambardella.github.io
        ref: dev  # Checkout the dev branch
        path: dist  # This checks out the GitHub Pages repo to the "work" directory

    - name: List output directory
      run: |
        ls -la src/output/

    - name: Copy markdown to GitHub Pages repo
      run: |
        cp src/output/hausing-scraper.md dist/src/content/work/hausing-scrapper.md

    - name: Commit changes to dev branch
      run: |
        cd dist  # Change to the dist directory
        git config --global user.email "celestegambardella.se@gmail.com"
        git config --global user.name "celestegambardella"
        current_time=$(date +"%Y-%m-%d %H:%M:%S")
        git add src/content/work/hausing-scrapper.md
        git commit -m "Update Hausing Scraper results at $current_time"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/celestegambardella/celestegambardella.github.io.git dev

    - name: Fetch prod branch
      run: |
        cd dist
        git fetch origin prod:prod  # Ensure the prod branch is fetched locally

    - name: Authenticate with GitHub CLI
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Create Pull Request from dev to prod
      run: |
        cd dist
        current_time=$(date +"%Y-%m-%d %H:%M:%S")
        gh pr create --base prod --head dev --title "Automated PR: Update Hausing Scraper ($current_time)" --body 
        "Automated update of Hausing Scraper results" --label "housing pr" --dry-run
#
#    # TODO use github cli for this
#    # TODO check for current git repos
#    # deleted any that might not be needed
#    # then create mr and merge
#
#    - name: Enable Pull Request Automerge for dev to prod
#      run: gh pr merge --repo celestegambardella/celestegambardella.io --merge --auto "1"
#      env:
#        GH_TOKEN: ${{ secrets.PAT }}
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
